# Generated by Django 2.2.2 on 2019-09-18 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseGroupInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_group_name', models.CharField(db_index=True, help_text='请输入用例组名称', max_length=32, verbose_name='用例组名称')),
                ('case_group_describe', models.CharField(blank=True, help_text='请输入用例组描述', max_length=255, null=True, verbose_name='用例组描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '用例组列表',
                'verbose_name_plural': '用例组列表',
                'db_table': 'case_group_info',
            },
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(db_index=True, help_text='请输入产品线名称', max_length=32, verbose_name='产品线名称')),
                ('product_describe', models.TextField(blank=True, help_text='请输入产品描述', null=True, verbose_name='产品描述')),
                ('product_manager', models.CharField(help_text='请输入产品经理', max_length=11, verbose_name='产品经理')),
                ('developer', models.CharField(blank=True, help_text='请输入开发人员', max_length=11, null=True, verbose_name='开发人员')),
                ('tester', models.CharField(blank=True, help_text='请输入测试人员', max_length=11, null=True, verbose_name='测试人员')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '产品线列表',
                'verbose_name_plural': '产品线列表',
                'db_table': 'product_info',
            },
        ),
        migrations.CreateModel(
            name='ModuleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(db_index=True, help_text='请输入模块名称', max_length=32, verbose_name='模块名称')),
                ('module_describe', models.TextField(blank=True, help_text='请输入模块描述', null=True, verbose_name='模块描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('module_group', models.ForeignKey(help_text='请选择产品线', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='interface.ProductInfo', verbose_name='产品线')),
            ],
            options={
                'verbose_name': '模块列表',
                'verbose_name_plural': '模块列表',
                'db_table': 'module_info',
            },
        ),
        migrations.CreateModel(
            name='InterfaceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(db_index=True, help_text='请输入用例名称', max_length=32, verbose_name='用例名称')),
                ('interface_url', models.CharField(help_text='请输入接口地址', max_length=255, verbose_name='接口地址')),
                ('request_mode', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH')], default='GET', help_text='请选择请求方式', max_length=11, verbose_name='请求方式')),
                ('request_parameter', models.TextField(blank=True, help_text='请输入字典格式的请求参数', null=True, verbose_name='请求参数')),
                ('request_head', models.TextField(help_text='请输入字典格式的请求头', verbose_name='请求头')),
                ('body_type', models.CharField(choices=[('x-www-form-urlencoded', 'application/x-www-form-urlencoded'), ('json', 'application/json'), ('form-data', 'multipart/form-data'), ('xml', 'text/xml')], default='x-www-form-urlencoded', help_text='请选择请求体类型', max_length=21, verbose_name='请求体类型')),
                ('request_body', models.TextField(blank=True, help_text='请输入键值对、json、文件或xml格式的请求体', null=True, verbose_name='请求体')),
                ('expected_result', models.TextField(blank=True, help_text='请输入预期结果', null=True, verbose_name='预期结果')),
                ('response_assert', models.CharField(blank=True, choices=[('包含', '包含'), ('相等', '相等')], default='包含', help_text='请选择断言方式', max_length=2, null=True, verbose_name='响应断言方式')),
                ('regular_expression', models.CharField(blank=True, choices=[('开启', '开启'), ('不开启', '不开启')], default='不开启', help_text='请选择是否开启正则表达式', max_length=3, null=True, verbose_name='开启正则表达式')),
                ('regular_variable', models.CharField(blank=True, help_text='请输入正则表达式变量名', max_length=11, null=True, verbose_name='正则表达式变量名')),
                ('regular_template', models.CharField(blank=True, help_text='请输入正则表达式模板', max_length=255, null=True, verbose_name='正则表达式模板')),
                ('response_code', models.IntegerField(blank=True, null=True, verbose_name='响应代码')),
                ('actual_result', models.TextField(blank=True, null=True, verbose_name='实际结果')),
                ('pass_status', models.BooleanField(blank=True, null=True, verbose_name='是否通过')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('case_group', models.ForeignKey(help_text='请选择用例组', on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='interface.CaseGroupInfo', verbose_name='用例组')),
            ],
            options={
                'verbose_name': '用例列表',
                'verbose_name_plural': '用例列表',
                'db_table': 'interface_info',
            },
        ),
    ]
